USE [master]
GO

/****** Object:  Database [DreamSky-RentShop]    Script Date: 19-Feb-20 1:35:20 PM ******/
CREATE DATABASE [DreamSky-RentShop]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DreamSky-RentShop', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\DreamSky-RentShop.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DreamSky-RentShop_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\DreamSky-RentShop_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DreamSky-RentShop].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DreamSky-RentShop] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DreamSky-RentShop] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DreamSky-RentShop] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DreamSky-RentShop] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DreamSky-RentShop] SET ARITHABORT OFF 
GO

ALTER DATABASE [DreamSky-RentShop] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DreamSky-RentShop] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DreamSky-RentShop] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DreamSky-RentShop] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DreamSky-RentShop] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DreamSky-RentShop] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DreamSky-RentShop] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DreamSky-RentShop] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DreamSky-RentShop] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DreamSky-RentShop] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DreamSky-RentShop] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DreamSky-RentShop] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DreamSky-RentShop] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DreamSky-RentShop] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DreamSky-RentShop] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DreamSky-RentShop] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DreamSky-RentShop] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DreamSky-RentShop] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DreamSky-RentShop] SET  MULTI_USER 
GO

ALTER DATABASE [DreamSky-RentShop] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DreamSky-RentShop] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DreamSky-RentShop] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DreamSky-RentShop] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DreamSky-RentShop] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DreamSky-RentShop] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DreamSky-RentShop] SET  READ_WRITE 
GO

